#!/usr/bin/env node debug
require('babel-polyfill');
require('babel-register');

if (process.argv[2]) {
    // eslint-disable-next-line global-require, import/no-dynamic-require
    require(`${process.cwd()}/${process.argv[2]}/app`);
} else {
    // eslint-disable-next-line global-require, import/no-dynamic-require
    require(`${process.cwd()}/app`);
}
